version: '3.8'
services:

  web:
    build: backend/.
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - backend/.env
    depends_on:
      - mongodb

  worker:
    build: worker/.
    volumes:
      - ./worker:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongoku:
    image: huggingface/mongoku
    container_name: mongoku
    ports:
      - "3100:3100"
    environment:
      MONGOKU_DEFAULT_HOST: "mongodb:27017"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
