version: '3.8'
services:

  web:
    build: backend/.
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - backend/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
