version: '3.8'
services:

  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - backend/.env
    depends_on:
      - mongodb

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - web
      - text_to_speech
    environment:
      - PYTHONUNBUFFERED=1

  text_to_speech:
    build:
      context: .
      dockerfile: ./text_to_speech/Dockerfile
    ports:
      - "7321:8000"
    volumes:
      - .:/app
      # so the model will not be redownloaded constantly
      - ./.models:/root/.local/share/tts/
      - ./.edge_nltk_data:/root/nltk_data/
    environment:
      - PYTHONUNBUFFERED=1
      # setting DUMMY_MODE in local shell turns on the dummy mode, otherwise it's standard. Dummy mode can be run with env DUMMY_MODE=1 docker-compose up --build
      - DUMMY_MODE=${DUMMY_MODE:-0}

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./.mongodb_data:/data/db

  mongoku:
    image: huggingface/mongoku
    container_name: mongoku
    ports:
      - "3100:3100"
    environment:
      MONGOKU_DEFAULT_HOST: "mongodb:27017"
    depends_on:
      - mongodb

  static_site:
    image: nginx:alpine
    volumes:
      - ./remove_newlines_website:/usr/share/nginx/html:ro
    ports:
      - "8080:80"


volumes:
  mongodb_data:
