version: '3.8'
services:

  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - backend/.env
    depends_on:
      - mongodb

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - web
    environment:
      - PYTHONUNBUFFERED=1

  text_to_speech:
    build:
      context: .
      dockerfile: ./text_to_speech/Dockerfile
    ports:
      - "7321:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongoku:
    image: huggingface/mongoku
    container_name: mongoku
    ports:
      - "3100:3100"
    environment:
      MONGOKU_DEFAULT_HOST: "mongodb:27017"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
