version: '3.8'
services:

  web:
    build: backend/.
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - backend/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
