name: Python Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]  # Adjust according to the Python versions you're targeting

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install black
      run: python -m pip install black

    - name: Run black (check mode)
      run: black --check .

